# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Summary
title: Jack Barker
description: > # this means to ignore newlines until "baseurl:"
  Jack Barker | 
  Business Analyst, Coder, Food Truck aficionado, and Mountain bike enthusiast.

# URL Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jackbarker.com.au" # the base hostname & protocol for your site

# Taxonomies
tag_page: '/tags/'

# Social / Contact info
twitter_username: jackbarker
github_username:  jibbius
linkedin:  https://au.linkedin.com/in/jackbarker1
mailhide:
  token: http://www.google.com/recaptcha/mailhide/d?k=01-sBNq2eC9n-vtrDvcD6OFA==&c=NLYXbMiWVrSGpjrhDXi-Vg-fye9Rr2HCkeUuiWUphmI=
  link-text: j.........
  domain-text: gmail.com

# Analytics
google_analytics: UA-40447110-1

#disqus
disqus:
  shortname:  jack-barker


# Build settings
markdown: kramdown
theme: minima

exclude:
  - .vscode
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - minima
  - versions.json

gems:
  - jemoji