#!/usr/bin/env bash
set -e # halt script on error

echo " Building Jekyll site..."
bundle exec jekyll build

echo "🔗 Running HTML validation..."
bundle exec htmlproofer ./_site --disable-external --assume-extension .html

echo "✅ Local build and validation complete!"